spring.application.name=plateformeBD
server.port=8081

# ===============================
# ? CONNEXION MARIA DB
# ===============================
spring.datasource.url=jdbc:mariadb://localhost:3306/plateformeBD
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===============================
# ?? HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.open-in-view=false

# ===============================
# ? EMAIL (MailHog ou SMTP local)
# ===============================
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ===============================
# ? JWT CONFIGURATION
# ===============================
# Cl� secr�te : 256 bits (format hexad�cimal ou Base64)
jwt.secret=608f36e92dc66d97d5933f0e6371493cb4fc05b1aa8f8de64014732472303a7c

# Dur�e de vie du token d?acc�s : 30 min (en millisecondes)
jwt.expiration.access=1800000

# Dur�e de vie du refresh token : 7 jours (en millisecondes)
jwt.expiration.refresh=604800000

# DEV
app.cookie.secure=false
app.cookie.samesite=Lax

# PROD (� changer)
# app.cookie.secure=true
# app.cookie.samesite=None